{% set name = "pyhull" %}
{% set version = "2015.2.1" %}
{% set md5 = "4437cae7f912c0829e504a9b22ac7626" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - pyhull

about:
  home: https://github.com/materialsvirtuallab/pyhull
  summary: 'A Python wrapper to Qhull (http://www.qhull.org/) for the computation of the convex hull, Delaunay triangulation and Voronoi diagram.'
  license_family: MIT
  description: |
    A Python wrapper to Qhull (http://www.qhull.org/) for the computation of
    the convex hull, Delaunay triangulation and Voronoi diagram.