{% set name = "atomate" %}
{% set version = "0.8.2" %}
{% set md5 = "951f51f91991e766a80a11e5f83b166e" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}  

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - fireworks >=1.6.8
    - pymatgen >=2018.2.13
    - pymatgen-diffusion >=2018.1.4
    - custodian >=2017.12.23
    - paramiko >=2.1.2
    - six
    - pybtex >=0.21

test:
  imports:
    - atomate
    - atomate.common
    - atomate.common.firetasks
    - atomate.feff
    - atomate.feff.firetasks
    - atomate.feff.fireworks
    - atomate.feff.workflows
    - atomate.lammps
    - atomate.lammps.firetasks
    - atomate.lammps.fireworks    
    - atomate.lammps.workflows
    - atomate.utils
    - atomate.vasp
    - atomate.vasp.analysis
    - atomate.vasp.builders
    - atomate.vasp.firetasks
    - atomate.vasp.fireworks
    - atomate.vasp.workflows
    - atomate.vasp.workflows.base
    - atomate.vasp.workflows.presets
  requires:
    - nose

about:
  home: https://hackingmaterials.github.io/atomate
  license: modified BSD
  license_family: BSD
  license_file: LICENSE
  summary: atomate has implementations of FireWorks workflows for Materials Science
  description: 'atomate is a powerful software for computational materials science and contains pre-built workflows.'
  doc_url: https://hackingmaterials.github.io/atomate
  dev_url: https://github.com/hackingmaterials/atomate  

extra:
  recipe-maintainers:
    - matk
    