{% set name = "gunicorn" %}
{% set version = "19.8.1" %}
{% set md5 = "4656b0edd6ad93c81d491e1448cc6c47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_django=gunicorn.app.djangoapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers

  commands:
    - gunicorn --help

about:
  home: http://gunicorn.org
  license: MIT License
  summary: 'WSGI HTTP Server for UNIX'
  license_family: MIT