{% set name = "tabulate" %}
{% set version = "0.8.2" %}
{% set md5 = "9bbaa53754356d837343740fdc70c074" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  entry_points:
    - tabulate = tabulate:_main
  number: 2
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - tabulate --help

about:
  home: https://bitbucket.org/astanin/python-tabulate
  license: MIT License
  summary: 'Pretty-print tabular data'
  license_family: MIT