{% set name = "seekpath" %}
{% set version = "1.1.0" %}
{% set md5 = "6dba94cba2313c6e17fdb9f6b8a1fad3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - spglib >=1.9.4
    - future >=0.15

  run:
    - python
    - numpy >=1.0
    - spglib >=1.9.4
    - future >=0.15

test:
  imports:
    - seekpath
    - seekpath.brillouinzone
    - seekpath.hpkot

about:
  home: http://github.com/giovannipizzi/seekpath
  license: MIT License
  summary: 'A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures'
  license_family: MIT
