{% set name = "spglib" %}
{% set version = "1.10.3.14" %}
{% set md5 = "d7041a65f483192b225977986713b4a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - vc9  # [win and py27]

  run:
    - python
    - numpy

test:
  imports:
    - spglib

about:
  home: http://atztogo.github.io/spglib/
  license: MIT
  summary: 'Spglib is a library for finding and handling crystal symmetries.'
  license_family: MIT
  description: |
    Spglib is a library for finding and handling crystal symmetries written in C. This is the
    Python extension version of spglib.