{% set name = "custodian" %}
{% set version = "2018.8.10" %}
{% set md5 = "cd47b289f81346a9d25d3e93c15a59bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  entry_points:
    - cstdn = custodian.cli.cstdn:main
    - run_vasp = custodian.cli.run_vasp:main
    - run_nwchem = custodian.cli.run_nwchem:main
    - converge_kpoints = custodian.cli.converge_kpoints:main
    - converge_geometry = custodian.cli.converge_geometry:main
  script: python setup.py install --single-version-externally-managed --record record.txt
  
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - monty >=1.0.2
    - six
    - ruamel.yaml >=0.15.35

test:
  imports:
    - custodian
    - custodian.ansible
    - custodian.cli
  commands:
    - cstdn --help

about:
  home: https://github.com/materialsproject/custodian
  license: MIT License
  summary: 'A simple JIT job management framework in Python.'
  license_family: MIT
  description: |
    Custodian is a simple, robust and flexible just-in-time (JIT) job management framework 
    written in Python. Using custodian, you can create wrappers that perform error checking, 
    job management and error recovery. It has a simple plugin framework that allows you to
    develop specific job management workflows for different applications. The current version
    of Custodian also comes with sub-packages for error handling for
    Vienna Ab Initio Simulation Package (VASP), NwChem and QChem calculations.