{% set name = "palettable" %}
{% set version = "3.1.0" %}
{% set md5 = "1fe822ae1379427360a2367e0cc588ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 2
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - palettable
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.tableau
    - palettable.wesanderson

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT License
  summary: 'Color palettes for Python'
  license_family: MIT
