{% set name = "palettable" %}
{% set version = "2.1.1" %}
{% set md5 = "60adcbda83e1eaa331c5fdc5dfbcc4ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch_python: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - palettable
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.tableau
    - palettable.wesanderson

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT License
  summary: 'Color palettes for Python'
  license_family: MIT
