{% set name = "ruamel.yaml" %}
{% set version = "0.16.4" %}
{% set md5 = "fbd24342e11be4e6fb6fcb4d9ba0a546" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: pip install .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - ruamel.yaml

about:
  home: https://github.com/materialsvirtuallab/monty
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ruamel.yaml'
  description: |
    ruamel.yaml is a YAML 1.2 loader/dumper package for Python.

extra:
  recipe-maintainers:
    - shyuep