{% set name = "pymatgen-db" %}
{% set version = "2018.2.21" %}
{% set md5 = "95d4e7383128fc8019c0d72b00ce198b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - pymatgen >=2018.2.13
    - monty >=1.0.2
    - pymongo >=2.8.0
    - smoqe
    - pybtex >=0.21
    - enum34  # [py27]

test:
  imports:
    - matgendb
    - matgendb.alchemy
    - matgendb.builders
    - matgendb.builders.examples
    - matgendb.tests
    - matgendb.vv

about:
  home: https://materialsproject.github.io/pymatgen-db/
  license: MIT License
  summary: 'Pymatgen-db is a database add-on for the Python Materials Genomics (pymatgen) materials analysis library.'
  description: |
    Pymatgen-db is a database add-on for the Python Materials Genomics (pymatgen) materials analysis library. It
    enables the creation of Materials Project-style MongoDB databases for management of materials data. A query engine
    is also provided to enable the easy translation of MongoDB docs to useful pymatgen objects for analysis purposes.
  dev_url: https://github.com/materialsproject/pymatgen-db

