{% set name = "BoltzTraP" %}
{% set version = "page" %}
{% set md5 = "d41d8cd98f00b204e9800998ecf8427e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://www.icams.de/content/uploads/{{ name|lower }}/{{ name }}.tar.bz2
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - gcc
    - m2w64-gcc-fortran # [win]
    - make # [win]

#test:
#  commands:
#    - x_trans -h

about:
  home: http://www.icams.de/research/software-development/boltztrap
  license: MIT
  summary: 'Boltzmann Transport Properties (BoltzTraP) is a program for calculating the semi-classic transport coefficients'
  description: |
    Boltzmann Transport Properties (BoltzTraP) is a program for calculating the semi-classic 
    transport coefficients. The code uses a mesh of self-consistent band energies and is 
    interfaced to the WIEN2k, AB-INIT, SIESTA, VASP and QuantumEspresso programs.