{% set name = "pybtex" %}
{% set version = "0.21" %}
{% set md5 = "e7b320b2bcb34c664c4385533a2ea831" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  entry_points:
    - pybtex = pybtex.__main__:main
    - pybtex-convert = pybtex.database.convert.__main__:main
    - pybtex-format = pybtex.database.format.__main__:main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  
requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.01
    - latexcodec >=1.0.2
  run:
    - python
    - setuptools
    - pyyaml >=3.01
    - latexcodec >=1.0.2

test:
  imports:
    - custom_fixers
    - pybtex
    - pybtex.backends
    - pybtex.bibtex
    - pybtex.charwidths
    - pybtex.database
    - pybtex.database.convert
    - pybtex.database.format
    - pybtex.database.input
    - pybtex.database.output
    - pybtex.markup
    - pybtex.plugin
    - pybtex.style
    - pybtex.style.formatting
    - pybtex.style.labels
    - pybtex.style.names
    - pybtex.style.sorting
    - pybtex.tests
    - pybtex.tests.bst_parser_test
    - pybtex.tests.data
    - pybtex.tests.database_test

  commands:
    - pybtex --help
    - pybtex-convert --help
    - pybtex-format --help

about:
  home: http://pybtex.org/
  license: MIT License
  summary: 'A BibTeX-compatible bibliography processor in Python'
  license_family: MIT
